name: FinanceMaker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.100'
  PROJECT_PATH: './FinanceMaker.Broker.Server'
  WORKER_PATH: './FinanceMaker.Worker'
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./**/TestResults/

  deploy-to-gcp:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and Push Broker Server
      run: |
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/financemaker-broker:${{ github.sha }} -f ${{ env.PROJECT_PATH }}/Dockerfile .
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/financemaker-broker:${{ github.sha }}
    
    - name: Build and Push Worker
      run: |
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/financemaker-worker:${{ github.sha }} -f ${{ env.WORKER_PATH }}/Dockerfile .
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/financemaker-worker:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy financemaker-broker \
          --image gcr.io/${{ env.GCP_PROJECT_ID }}/financemaker-broker:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
        
        gcloud run deploy financemaker-worker \
          --image gcr.io/${{ env.GCP_PROJECT_ID }}/financemaker-worker:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated 